# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proyecto < Formula
  desc "Proyecto is a lightweight CLI tool for managing local projects"
  homepage ""
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GloryWong/proyecto/releases/download/v1.3.3/proyecto_1.3.3_darwin_amd64"
      sha256 "bdb7affb590cbb3d48e09409c7aadea176029b9e58d617cabdf1c114382278ac"

      def install
        bin.install "proyecto_1.3.3_darwin_amd64" => "proyecto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GloryWong/proyecto/releases/download/v1.3.3/proyecto_1.3.3_darwin_arm64"
      sha256 "3b8522f0c6b8c6b005a62f84a052cef8f03cd107135222255811b78026086ff2"

      def install
        bin.install "proyecto_1.3.3_darwin_arm64" => "proyecto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GloryWong/proyecto/releases/download/v1.3.3/proyecto_1.3.3_linux_amd64"
        sha256 "22750e6367a6b8161b5f69deb5eaf4cf36f092bb9e929121677324c14b67111d"

        def install
          bin.install "proyecto_1.3.3_linux_amd64" => "proyecto"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GloryWong/proyecto/releases/download/v1.3.3/proyecto_1.3.3_linux_arm64"
        sha256 "031d4abb9598402971432674965b9fefaf176a3f8ab0083f115b84368974f90a"

        def install
          bin.install "proyecto_1.3.3_linux_arm64" => "proyecto"
        end
      end
    end
  end

  def caveats
    <<~EOS
      proyecto --help
    EOS
  end

  test do
    system "#{bin}/proyecto --version"
  end
end
