# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Proyecto < Formula
  desc "Proyecto is a lightweight CLI tool for managing local projects"
  homepage "https://github.com/GloryWong/proyecto"
  version "2.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GloryWong/proyecto/releases/download/v2.5.3/proyecto_2.5.3_darwin_amd64.tar.gz"
      sha256 "ca2768d90b679afc92221c764144f49c1141fd42f63f6d72313bfbf4863f1c4a"

      define_method(:install) do
        bin.install "proyecto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GloryWong/proyecto/releases/download/v2.5.3/proyecto_2.5.3_darwin_arm64.tar.gz"
      sha256 "1ce8c20616b77f194738d9497efa3958d1f95a4f261e4753387ed81b8e03a785"

      define_method(:install) do
        bin.install "proyecto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GloryWong/proyecto/releases/download/v2.5.3/proyecto_2.5.3_linux_amd64.tar.gz"
      sha256 "f19398aaa8c58e902f250b4c8e7b8d14a2b5b376d2761be67af66272f5b20d0d"
      define_method(:install) do
        bin.install "proyecto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GloryWong/proyecto/releases/download/v2.5.3/proyecto_2.5.3_linux_arm64.tar.gz"
      sha256 "02de6d7cbe425627a7c21264cbe1326f693112d404fdbb9603a53aef3d7df76e"
      define_method(:install) do
        bin.install "proyecto"
      end
    end
  end

  def caveats
    <<~EOS
      proyecto --help
    EOS
  end

  test do
    system "#{bin}/proyecto --version"
  end
end
