# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updown < Formula
  desc "A CLI tool to upload or download files to or from GitHub Gist"
  homepage "https://github.com/robertwang1001/updown"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robertwang1001/updown/releases/download/v1.6.0/updown_1.6.0_darwin_amd64.tar.gz"
      sha256 "9d0af2e7dc2707ca2dcaeba72901e852556d9afbb9d41df5a67cb7deefe056ee"

      define_method(:install) do
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robertwang1001/updown/releases/download/v1.6.0/updown_1.6.0_darwin_arm64.tar.gz"
      sha256 "f3a18225c79aa3b898628b4cb586bde6de91328cde75c4dd7d858205b8b5f85c"

      define_method(:install) do
        bin.install "updown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robertwang1001/updown/releases/download/v1.6.0/updown_1.6.0_linux_amd64.tar.gz"
      sha256 "7842e916bb3cf9a9ae235a1a5d0cdf479ceb6f9954642522e647edfe6e76fc47"
      define_method(:install) do
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robertwang1001/updown/releases/download/v1.6.0/updown_1.6.0_linux_arm64.tar.gz"
      sha256 "972b70d244bc6f739f7af03366670f60d9355d2942db3bad34db57fb6f97a23d"
      define_method(:install) do
        bin.install "updown"
      end
    end
  end

  def post_install
    # Ensure the ~/.updown/logs directory exists
    (Pathname.new(Dir.home)/".updown/logs").mkpath
  end

  def caveats
    <<~EOS
      updown --help
    EOS
  end

  service do
    run [opt_bin/"updown", "upload", "--quiet", "--notify"]
    run_type :cron
    cron "0 15 * * *" # 15:00 every day
    log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.log"
    error_log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.error.log"
    environment_variables PATH: std_service_path_env
  end

  test do
    system "#{bin}/updown --version"
  end
end
