# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updown < Formula
  desc "A CLI tool to upload or download files to or from GitHub Gist"
  homepage "https://github.com/GloryWong/updown"
  version "1.5.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GloryWong/updown/releases/download/v1.5.8/updown_1.5.8_darwin_amd64.tar.gz"
      sha256 "3cec8da9a06af347fd52f95c292a702f398035bcbdb324b8a4b7c1138e6ddb1b"

      def install
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GloryWong/updown/releases/download/v1.5.8/updown_1.5.8_darwin_arm64.tar.gz"
      sha256 "82bb710bb3cfbb76de389261f1279093557cc7ee28c125b2f091cfa27f252faa"

      def install
        bin.install "updown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/GloryWong/updown/releases/download/v1.5.8/updown_1.5.8_linux_amd64.tar.gz"
      sha256 "f7e88c0e632dbcaca601e613856a90cc2c41d8b150b39c11b0e9ea62101c2838"
      def install
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GloryWong/updown/releases/download/v1.5.8/updown_1.5.8_linux_arm64.tar.gz"
      sha256 "ee7a8d0c383f03c0f0d41f04b25472e2b1530a56440c453c942bb91f16239ef5"
      def install
        bin.install "updown"
      end
    end
  end

  def post_install
    # Ensure the ~/.updown/logs directory exists
    (Pathname.new(Dir.home)/".updown/logs").mkpath
  end

  def caveats
    <<~EOS
      updown --help
    EOS
  end

  service do
    run [opt_bin/"updown", "upload", "--quiet", "--notify"]
    run_type :cron
    cron "0 15 * * *" # 15:00 every day
    log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.log"
    error_log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.error.log"
    environment_variables PATH: std_service_path_env
  end

  test do
    system "#{bin}/updown --version"
  end
end
