# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Updown < Formula
  desc "A CLI tool to upload or download files to or from GitHub Gist"
  homepage "https://github.com/GloryWong/updown"
  version "1.5.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GloryWong/updown/releases/download/v1.5.6/updown_1.5.6_darwin_amd64.tar.gz"
      sha256 "2df93ee162fd7bde9a7f8dc235452c1036a759c22e4719f8e36b3e6442f9ec89"

      def install
        bin.install "updown"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GloryWong/updown/releases/download/v1.5.6/updown_1.5.6_darwin_arm64.tar.gz"
      sha256 "ead89471a415b73358f4b8319f20796b192c9298a073a503654beefe7a6fc704"

      def install
        bin.install "updown"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GloryWong/updown/releases/download/v1.5.6/updown_1.5.6_linux_amd64.tar.gz"
        sha256 "eb5dfbca84a8752aed0bcb4e4675c09e6cd7cf0e71ad3432bc3635375c3990c9"

        def install
          bin.install "updown"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GloryWong/updown/releases/download/v1.5.6/updown_1.5.6_linux_arm64.tar.gz"
        sha256 "a81349ecc5b0308a9a7bf8991518c21c590e3d2c08208a76a76ca51718335c93"

        def install
          bin.install "updown"
        end
      end
    end
  end

  def post_install
    # Ensure the ~/.updown/logs directory exists
    (Pathname.new(Dir.home)/".updown/logs").mkpath
  end

  def caveats
    <<~EOS
      updown --help
    EOS
  end

  service do
    run [opt_bin/"updown", "upload", "--quiet", "--notify"]
    run_type :cron
    cron "0 15 * * *" # 15:00 every day
    log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.log"
    error_log_path Pathname.new(Dir.home)/".updown/logs/updown-brew-service.error.log"
    environment_variables PATH: std_service_path_env
  end

  test do
    system "#{bin}/updown --version"
  end
end
