# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherCli < Formula
  desc "A CLI tool to upload or download files to or from GitHub Gist"
  homepage "https://github.com/GloryWong/weather-cli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GloryWong/weather-cli/releases/download/v1.2.0/weather-cli_1.2.0_darwin_amd64.tar.gz"
      sha256 "01e3202695fe9c7279db4bf6f850b83c3d5fa7a5401ce34719808fcde0b673bd"

      def install
        bin.install "weather"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GloryWong/weather-cli/releases/download/v1.2.0/weather-cli_1.2.0_darwin_arm64.tar.gz"
      sha256 "35d553a0fd5dee21378e78af72c042aaeea35ae57564de231e245c0970579125"

      def install
        bin.install "weather"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GloryWong/weather-cli/releases/download/v1.2.0/weather-cli_1.2.0_linux_amd64.tar.gz"
        sha256 "01f11571abccd98d3be8a907c908b59bbb5278fb7bb1c5e77ee3ff7b814b212a"

        def install
          bin.install "weather"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GloryWong/weather-cli/releases/download/v1.2.0/weather-cli_1.2.0_linux_arm64.tar.gz"
        sha256 "984fdcedc999c12bdf3c57569dab46f046097eb254e8f25ce0479826856d4923"

        def install
          bin.install "weather"
        end
      end
    end
  end

  def caveats
    <<~EOS
      weather --help
    EOS
  end

  test do
    system "#{bin}/weather --version"
  end
end
