# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeatherCli < Formula
  desc "A CLI tool to upload or download files to or from GitHub Gist"
  homepage "https://github.com/GloryWong/weather-cli"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GloryWong/weather-cli/releases/download/v1.2.1/weather-cli_1.2.1_darwin_amd64.tar.gz"
      sha256 "0ba17c750163e9afcb577597bb1a1f8d5ca9823bd8bbc30d4eedf5694b84d1c4"

      def install
        bin.install "weather"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/GloryWong/weather-cli/releases/download/v1.2.1/weather-cli_1.2.1_darwin_arm64.tar.gz"
      sha256 "c58fbc940f3828df234b8cbc181d7e08e7ae3056ff6bdd2acc71a1fc71a8c09f"

      def install
        bin.install "weather"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GloryWong/weather-cli/releases/download/v1.2.1/weather-cli_1.2.1_linux_amd64.tar.gz"
        sha256 "a38a735928d5aee26b7bd5d71426d138c27e5e54da6313d5b82156457cadb885"

        def install
          bin.install "weather"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/GloryWong/weather-cli/releases/download/v1.2.1/weather-cli_1.2.1_linux_arm64.tar.gz"
        sha256 "8ca999d5b5e4c885354b38c484b10e0b0d52c1574a5a5e3c26efad180ed197ab"

        def install
          bin.install "weather"
        end
      end
    end
  end

  def caveats
    <<~EOS
      weather --help
    EOS
  end

  test do
    system "#{bin}/weather --version"
  end
end
